// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_MapInt from "bs-platform/lib/es6/belt_MapInt.js";

var set = Belt_MapInt.set;

var empty;

var get = Belt_MapInt.getUndefined;

export {
  set ,
  empty ,
  get ,
  
}
/* No side effect */
